#!/bin/bash

# USAGE: ./bastion-ssh

set -x

state_file="${STATE_FILE:-./terraform.tfstate}"

#You need the sed nonsense if the path to your key has a ~ in it
keyPath=$(terraform output -state="${state_file}" aws_key_path | sed -e "s#^~#$HOME#")
scriptPath="provision/provision.sh"
targetPath="/home/ubuntu/provision.sh"
bastionIP=$(terraform output -state="${state_file}" bastion_ip)

ssh -i ${keyPath} ubuntu@$bastionIP
